const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { chromium } = require('playwright');
const story = require('../assets/js/about-me-story-core');
const options = require('../assets/data/about_me_options.json');
const sample = { name: 'Artur', age: '36', years: '5', origin: 'mill-Ukraina', residence: 'il-Mosta', occupation: 'programmatur', workDetail: 'nikteb programmi', workDetailEnglish: 'I write programs', hobbies: 'naqra', hobbiesEnglish: 'read', relationship: 'married', spouseName: 'Sara', children: 'two', child1Name: 'Ivan', child1Gender: 'male', child1Age: '9', child2Name: 'Kira', child2Gender: 'female', child2Age: '6', numberWords: true, childrenSchool: true, familyLikesMalta: true, learningReason: 'people' };
assert.equal(story.numberWords(36), 'sitta u tletin');
assert.equal(story.numberWords(5), 'ħamsa');
for (const [number, expected] of [[0, 'żero snin'], [1, 'sena'], [2, 'sentejn'], [3, 'tliet snin'], [4, "erba' snin"], [5, 'ħames snin'], [9, "disa' snin"], [11, 'ħdax-il sena'], [19, 'dsatax-il sena'], [20, 'għoxrin sena'], [36, 'sitta u tletin sena'], [100, 'mitt sena'], [120, '120 sena']]) assert.equal(story.yearPhrase(number, true), expected);
const rows = story.rows(sample, options);
assert.ok(rows.every((row) => row.english && row.question && row.questionEnglish));
assert.match(story.copyText(rows, true), /Għandi sitta u tletin sena\.\nI am 36 years old\./);
assert.match(story.copyText(rows, true), /Għandha sitt snin\.\nKira is 6 years old\./);
assert.ok(!story.copyText(rows, false).includes('I am'));
assert.ok(!story.rows({ ...sample, storyVersion: 'short' }, options).some((row) => ['duration', 'duties', 'spouse', 'child1Name', 'school', 'motivation'].includes(row.id)));
assert.ok(!story.rows({ ...sample, includeFamily: false }, options).some((row) => ['family', 'children'].includes(row.topic)));
assert.equal(story.rows({ ...sample, children: 'one', child1Gender: 'female' }, options).find((row) => row.id === 'school').maltese, 'Binti tmur l-iskola.');
assert.ok(!story.rows({ ...sample, children: 'none' }, options).some((row) => row.id === 'school'));
assert.throws(() => story.copyText(story.rows({ ...sample, workDetailEnglish: '' }, options), true), /missing English/);
assert.ok(!story.rows({ age: '-1', years: '1.5' }, options).length);
assert.equal(story.rows({ age: '1' }, options)[0].english, 'I am 1 year old.');
const base = process.env.LESSON01_URL || 'http://127.0.0.1:4190';
(async () => {
    const browser = await chromium.launch({ executablePath: 'C:/Program Files/Google/Chrome/Application/chrome.exe', headless: true });
    const errors = [];
    const directory = path.resolve('visual-regression/screenshots/about-me-builder');
    fs.mkdirSync(directory, { recursive: true });
    try {
        for (const width of [1280, 390]) {
            const context = await browser.newContext({ viewport: { width, height: 1000 }, serviceWorkers: 'block' });
            const page = await context.newPage();
            page.on('pageerror', (error) => errors.push(error.message));
            await page.goto(base + '/about_me.html#builder');
            await page.waitForFunction(() => document.querySelector('[data-about-me-practice]')?.dataset.aboutMeReady === 'true');
            await page.locator('[data-about-me-sample]').click();
            await page.locator('[name="age"]').fill('36');
            await page.locator('[name="numberWords"]').check();
            assert.match(await page.locator('[data-about-me-output]').innerText(), /Għandi sitta u tletin sena/);
            assert.match(await page.locator('[data-about-me-output]').innerText(), /għal ħames snin/);
            await page.evaluate(() => Object.defineProperty(navigator.clipboard, 'writeText', { configurable: true, value: async (text) => { window.copiedStory = text; } }));
            await page.locator('[name="copyFormat"]').selectOption('bilingual');
            await page.locator('[data-about-me-copy]').click();
            assert.equal(await page.evaluate(() => window.copiedStory), await page.evaluate(() => window.MaltiStoryCore.copyText(window.MaltiAboutMe.getStoryRows(), true)));
            await page.locator('[name="showEnglish"]').uncheck();
            assert.equal(await page.locator('.about-me-story-english').count(), 0);
            await page.locator('[data-about-me-copy]').click();
            assert.match(await page.evaluate(() => window.copiedStory), /My name is Alex/);
            await page.locator('[name="copyFormat"]').selectOption('maltese');
            await page.locator('[data-about-me-copy]').click();
            assert.equal(await page.evaluate(() => window.copiedStory), await page.evaluate(() => window.MaltiAboutMe.getStory().join('\n')));
            await page.locator('[name="storyVersion"]').selectOption('short');
            assert.ok(!(await page.locator('[data-about-me-output]').innerText()).includes('Luca'));
            await page.locator('[name="storyVersion"]').selectOption('full');
            await page.locator('[name="childrenSchool"]').check();
            await page.locator('[name="familyLikesMalta"]').check();
            await page.locator('[name="learningReason"]').selectOption('people');
            assert.match(await page.locator('[data-about-me-output]').innerText(), /It-tfal tiegħi jmorru l-iskola/);
            await page.locator('[data-personal-support]').selectOption('none');
            assert.equal(await page.locator('[data-personal-answer]').isVisible(), false);
            await page.locator('[data-personal-reveal]').click();
            assert.equal(await page.locator('[data-personal-answer]').innerText(), 'Jisimni Alex.');
            await page.locator('[data-personal-next]').click();
            assert.equal(await page.locator('[data-personal-answer]').isVisible(), false);
            await page.locator('[data-personal-support]').selectOption('keywords');
            assert.ok((await page.locator('[data-personal-answer]').innerText()).length > 0);
            await page.locator('[data-about-me-save]').click();
            await page.reload();
            await page.waitForFunction(() => document.querySelector('[data-about-me-practice]')?.dataset.aboutMeReady === 'true');
            assert.equal(await page.locator('[name="numberWords"]').isChecked(), true);
            assert.equal(await page.locator('[name="showEnglish"]').isChecked(), false);
            assert.equal(await page.locator('[name="workDetailEnglish"]').inputValue(), 'I teach Maltese and prepare lessons');
            await page.locator('[name="showEnglish"]').check();
            await page.locator('[name="occupation"]').fill('custom job');
            await page.locator('[name="copyFormat"]').selectOption('bilingual');
            await page.evaluate(() => { window.copiedStory = 'unchanged'; Object.defineProperty(navigator.clipboard, 'writeText', { configurable: true, value: async (text) => { window.copiedStory = text; } }); });
            await page.locator('[data-about-me-copy]').click();
            assert.equal(await page.evaluate(() => window.copiedStory), 'unchanged');
            assert.match(await page.locator('[data-about-me-builder-status]').innerText(), /missing English/);
            await page.locator('[name="occupationEnglish"]').fill('engineer');
            await page.locator('[data-about-me-copy]').click();
            assert.match(await page.evaluate(() => window.copiedStory), /I work as an engineer/);
            assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
            await page.locator('#builder h2').click();
            await page.mouse.move(width - 5, 950);
            await page.screenshot({ path: path.join(directory, 'builder-' + width + '.png') });
            await page.locator('[data-personal-practice]').scrollIntoViewIfNeeded();
            await page.screenshot({ path: path.join(directory, 'practice-' + width + '.png') });
            await page.locator('[data-about-me-clear]').click();
            assert.equal(await page.locator('[name="numberWords"]').isChecked(), false);
            assert.equal(await page.locator('[name="workDetailEnglish"]').inputValue(), '');
            assert.equal(await page.evaluate(() => localStorage.getItem('malti_about_me_draft_v1')), null);
            await context.close();
        }
        assert.deepEqual(errors, []);
        console.log('PASS: English rows, word numbers, full/short details, family extras, personal hints, both copy formats, missing translation guard, persistence and desktop/mobile layout.');
    } finally { await browser.close(); }
})().catch((error) => { console.error(error); process.exitCode = 1; });
